### ISSUE TITLE
откуда получили client_secret ключ? Объясните все.

### ISSUE THREAD

**Issue by homus32** [vodka2/vkaudiotoken-python#1]
```python
VK_OFFICIAL = VkClient(
    u'VKAndroidApp/5.52-4543 (Android 5.1.1; SDK 22; x86_64; unknown Android SDK built for x86_64; en; 320x240)',
    u'hHbZxrka2uZ6jB1inYsH',
    u'2274003'
)
```
Второй параметр

Мне вообще интересно как вы разобрались во всем этом. Объясните пожалуйста

**Comment by vodka2** [comment]
@homus32 очевидно, что client_secret получен анализом исходного кода клиента и анализом запросов к сети, которые он делает. Там простой пиннинг вроде, по крайней мере в той версии.
Насчёт «как вы разобрались во всём этом» — лучше написать конкретные вопросы.
